services:
  - type: web
    name: egyptian-audit-solution
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: XAI_API_KEY
        sync: false
    domains:
      - egyptian-audit-solution.onrender.com
